### ISSUE TITLE
Support for worldwide base layers

### ISSUE THREAD

**Issue by elafargue** [PolaricServer/webapp#1]
This is more a question than an actual issue (congrats on this project by the way!): is there anything that prevents PolaricServer webapp from using OSM or Google Openlayers layers, apart from the fact support is not in the compiled javascript?

It would be great to offer a basic OpenStreetmaps or Google Maps "worldwide" layer to allow users outside of Europe to try Polaric Server. If I implement this, I will submit a pull request...

**Comment by ohanssen** [comment]
Ok, with the lastest updates I consider this as resolved and close this issue. There are still some issues when crossing the dateline but it depends on the projection how this can be solved.
