### ISSUE TITLE
Wheel zoom on cursor

### ISSUE THREAD

**Issue by stratus9** [PolaricServer/webapp#21]
Is there possibility to change wheel zoom behavior that it sets center of scaling on cursor instead of center of the map?

**Comment by ohanssen** [comment]
I see your point and will try to fix it if there is an updated release of the old webapp. In the new client implementation (see webapp2) it will work the right way.

**Comment by ohanssen** [comment]
I made a hack that fixes it. Checking it in a litter later today.
