### ISSUE TITLE
Recurring issue on scalebar

### ISSUE THREAD

**Issue by elafargue** [PolaricServer/webapp#9]
I have noticed that the scalebar.js script sometimes errors with "allRules" being undefined.

Specifically line 161 in scalebar.js (https://github.com/PolaricServer/webapp/blob/master/KaMap/scalebar/scalebar.js#L161)

Adding a simple (if allRules) test before the 'for' loop solves the issue.

It looks like the script triggering an error prevents the loading of further tile maps, resulting in empty map backgrounds (verified on Google Terrain maps).

**Comment by ohanssen** [comment]
Ok, I added the test.
